strict-sigcheck = false
build-changed-only = ["hoo-dles"]

[Twitter-Piko]
enabled = true
app-name = "Twitter"
patches-source = "github:crimera/piko"
cli-source = "github:MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
version = "auto"
# version = "11.81.0-release.0" # PairIP Free
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Bring back twitter' \
    'Dynamic color' \
    """
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/x-twitter"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
skip-sigcheck = true

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "github:MorpheApp/morphe-patches"
cli-source = "github:MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # "20.51.39"
# Experimental Support #
# version = "21.21.91"
version = "21.22.165"
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
