strict-sigcheck = false

[Twitter-Piko]
enabled = true
app-name = "Twitter"
patches-source = "github:crimera/piko"
cli-source = "github:MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
version = "auto"
# version = "11.81.0-release.0" # PairIP Free
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Bring back twitter' \
    'Browse tweet object' \
    'Dynamic color' \
    """
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/x-twitter"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
skip-sigcheck = true
